//! Closed (transitive) edit-cost maps from a unified token graph.
//!
//! [`compute_closed_cost_maps`] seeds one graph from the raw sub/ins/del maps,
//! grows the node set by applying configured ins/del transformations until
//! fixpoint, closes the graph with Floyd-Warshall, and projects distances back
//! into three plain cost maps:
//!   - `dist[a][b]` for substitutions,
//!   - `dist[a][ε]` for deletions,
//!   - `dist[ε][b]` for insertions.

use crate::cost_map::CostMap;
use crate::types::{SingleTokenCostMap, SingleTokenKey, SubstitutionCostMap, SubstitutionKey};
use std::collections::{HashMap, HashSet};

// Configured tokens up to this length are expanded into all of their substrings,
// and intermediate nodes generated by ins/del growth are also capped at this
// length. Floyd-Warshall is O(N³) over the resulting node set.
const MAX_NODE_LENGTH_CHARS: usize = 8;

// Hard caps on iterative node growth so pathological inputs cannot explode the
// graph. Once these are hit, growth stops; closure runs on whatever nodes exist.
const MAX_NODES: usize = 2048;
const MAX_GROWTH_ROUNDS: usize = 3;

/// Interned identifier for a token graph node.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
struct NodeId(u32);

impl NodeId {
    fn new(index: usize) -> Self {
        assert!(index < u32::MAX as usize, "too many token graph nodes");
        Self(index as u32)
    }

    #[inline]
    fn index(self) -> usize {
        self.0 as usize
    }
}

/// Dense square matrix stored in row-major order.
#[derive(Debug)]
struct Matrix<T> {
    width: usize,
    cells: Vec<T>,
}

impl<T: Clone> Matrix<T> {
    fn filled(width: usize, value: T) -> Self {
        Self {
            width,
            cells: vec![value; width * width],
        }
    }
}

impl<T> Matrix<T> {
    #[inline]
    fn idx(&self, row: NodeId, col: NodeId) -> usize {
        row.index() * self.width + col.index()
    }

    #[inline]
    fn get(&self, row: NodeId, col: NodeId) -> &T {
        &self.cells[self.idx(row, col)]
    }

    #[inline]
    fn set(&mut self, row: NodeId, col: NodeId, value: T) {
        let idx = self.idx(row, col);
        self.cells[idx] = value;
    }
}

/// Computes closed sub/ins/del cost maps via Floyd-Warshall on a unified graph.
pub fn compute_closed_cost_maps(
    sub: &CostMap<SubstitutionKey>,
    ins: &CostMap<SingleTokenKey>,
    del: &CostMap<SingleTokenKey>,
) -> (SubstitutionCostMap, SingleTokenCostMap, SingleTokenCostMap) {
    let tokens = collect_nodes(sub, ins, del);
    let token_to_id: HashMap<&str, NodeId> = tokens
        .iter()
        .enumerate()
        .map(|(i, token)| (token.as_str(), NodeId::new(i)))
        .collect();
    let epsilon_id = token_to_id[""];
    let dist = run_closure(&tokens, &token_to_id, epsilon_id, sub, ins, del);

    let closed_sub = project_substitutions(&tokens, &token_to_id, &dist, sub);
    let closed_ins = project_single_token(&tokens, &token_to_id, &dist, ins, epsilon_id, true);
    let closed_del = project_single_token(&tokens, &token_to_id, &dist, del, epsilon_id, false);

    (closed_sub, closed_ins, closed_del)
}

/// Collects graph nodes. Includes raw tokens, all substrings of raw tokens, and
/// strings reachable by iteratively applying configured ins/del transformations
/// (bounded by length, total count, and round cap).
fn collect_nodes(
    sub: &CostMap<SubstitutionKey>,
    ins: &CostMap<SingleTokenKey>,
    del: &CostMap<SingleTokenKey>,
) -> Vec<String> {
    let mut tokens: HashSet<String> = HashSet::new();
    tokens.insert(String::new()); // ε
    tokens.extend(ins.costs.keys().cloned());
    tokens.extend(del.costs.keys().cloned());
    for (s, t) in sub.costs.keys() {
        tokens.insert(s.clone());
        tokens.insert(t.clone());
    }

    let seeds: Vec<String> = tokens.iter().cloned().collect();
    for token in &seeds {
        for substring in substrings(token) {
            tokens.insert(substring);
        }
    }

    // Configured ins/del tokens are applied in BOTH directions to grow the set:
    // inserting them produces forward-direction successors, removing them
    // produces predecessors that lie one configured ins/del edge away. This is
    // what lets the closure bridge a user-provided source like "ADC" through
    // intermediate nodes "AC" and "ABC" to a configured target "Z".
    let single_op_tokens: Vec<String> = ins
        .costs
        .keys()
        .cloned()
        .chain(del.costs.keys().cloned())
        .collect::<HashSet<_>>()
        .into_iter()
        .collect();

    'rounds: for _ in 0..MAX_GROWTH_ROUNDS {
        let snapshot: Vec<String> = tokens.iter().cloned().collect();
        let prev_size = snapshot.len();

        for source in &snapshot {
            let source_len = source.chars().count();
            for op_token in &single_op_tokens {
                if source_len + op_token.chars().count() <= MAX_NODE_LENGTH_CHARS {
                    for variant in insert_token_variants(source, op_token) {
                        tokens.insert(variant);
                        if tokens.len() >= MAX_NODES {
                            break 'rounds;
                        }
                    }
                }
                for variant in delete_token_variants(source, op_token) {
                    tokens.insert(variant);
                    if tokens.len() >= MAX_NODES {
                        break 'rounds;
                    }
                }
            }
        }

        if tokens.len() == prev_size {
            break;
        }
    }

    tokens.into_iter().collect()
}

fn substrings(token: &str) -> Vec<String> {
    let char_count = token.chars().count();
    if char_count > MAX_NODE_LENGTH_CHARS {
        return Vec::new();
    }
    let mut boundaries: Vec<usize> = token.char_indices().map(|(idx, _)| idx).collect();
    boundaries.push(token.len());

    let mut out = Vec::with_capacity(char_count * (char_count + 1) / 2);
    for start in 0..char_count {
        for end in (start + 1)..=char_count {
            out.push(token[boundaries[start]..boundaries[end]].to_owned());
        }
    }
    out
}

/// All strings obtainable by inserting `inserted` at a char boundary in `source`.
fn insert_token_variants(source: &str, inserted: &str) -> Vec<String> {
    source
        .char_indices()
        .map(|(idx, _)| idx)
        .chain(std::iter::once(source.len()))
        .map(|idx| {
            let mut target = String::with_capacity(source.len() + inserted.len());
            target.push_str(&source[..idx]);
            target.push_str(inserted);
            target.push_str(&source[idx..]);
            target
        })
        .collect()
}

/// All strings obtainable by deleting one exact `deleted` occurrence from `source`.
fn delete_token_variants(source: &str, deleted: &str) -> Vec<String> {
    source
        .match_indices(deleted)
        .map(|(idx, _)| {
            let end = idx + deleted.len();
            let mut target = String::with_capacity(source.len() - deleted.len());
            target.push_str(&source[..idx]);
            target.push_str(&source[end..]);
            target
        })
        .collect()
}

fn run_closure(
    tokens: &[String],
    token_to_id: &HashMap<&str, NodeId>,
    epsilon_id: NodeId,
    sub: &CostMap<SubstitutionKey>,
    ins: &CostMap<SingleTokenKey>,
    del: &CostMap<SingleTokenKey>,
) -> Matrix<f64> {
    let n = tokens.len();
    let mut dist = Matrix::filled(n, f64::INFINITY);

    for index in 0..n {
        let node = NodeId::new(index);
        dist.set(node, node, 0.0);
    }

    for ((source, target), &cost) in &sub.costs {
        if let (Some(&s), Some(&t)) =
            (token_to_id.get(source.as_str()), token_to_id.get(target.as_str()))
        {
            relax(&mut dist, s, t, cost);
        }
    }

    for (token, &cost) in &ins.costs {
        if let Some(&id) = token_to_id.get(token.as_str()) {
            relax(&mut dist, epsilon_id, id, cost);
        }
    }

    for (token, &cost) in &del.costs {
        if let Some(&id) = token_to_id.get(token.as_str()) {
            relax(&mut dist, id, epsilon_id, cost);
        }
    }

    seed_embedded_edges(tokens, token_to_id, ins, del, &mut dist);
    floyd_warshall(&mut dist);
    dist
}

#[inline]
fn relax(dist: &mut Matrix<f64>, source: NodeId, target: NodeId, cost: f64) {
    if cost < *dist.get(source, target) {
        dist.set(source, target, cost);
    }
}

/// Adds direct edges between two existing nodes that differ by exactly one
/// configured insertion or deletion.
fn seed_embedded_edges(
    tokens: &[String],
    token_to_id: &HashMap<&str, NodeId>,
    ins: &CostMap<SingleTokenKey>,
    del: &CostMap<SingleTokenKey>,
    dist: &mut Matrix<f64>,
) {
    let insertions: Vec<(&str, f64)> = ins
        .costs
        .iter()
        .map(|(token, &cost)| (token.as_str(), cost))
        .collect();
    let deletions: Vec<(&str, f64)> = del
        .costs
        .iter()
        .map(|(token, &cost)| (token.as_str(), cost))
        .collect();

    for source in tokens {
        let source_id = token_to_id[source.as_str()];
        for &(inserted, cost) in &insertions {
            for variant in insert_token_variants(source, inserted) {
                if let Some(&target_id) = token_to_id.get(variant.as_str()) {
                    relax(dist, source_id, target_id, cost);
                }
            }
        }
        for &(deleted, cost) in &deletions {
            for variant in delete_token_variants(source, deleted) {
                if let Some(&target_id) = token_to_id.get(variant.as_str()) {
                    relax(dist, source_id, target_id, cost);
                }
            }
        }
    }
}

fn floyd_warshall(dist: &mut Matrix<f64>) {
    let n = dist.width;
    for via in 0..n {
        let via = NodeId::new(via);
        for source in 0..n {
            let source = NodeId::new(source);
            let source_to_via = *dist.get(source, via);
            if !source_to_via.is_finite() {
                continue;
            }
            for target in 0..n {
                let target = NodeId::new(target);
                let candidate = source_to_via + *dist.get(via, target);
                if candidate < *dist.get(source, target) {
                    dist.set(source, target, candidate);
                }
            }
        }
    }
}

fn project_substitutions(
    tokens: &[String],
    token_to_id: &HashMap<&str, NodeId>,
    dist: &Matrix<f64>,
    raw: &CostMap<SubstitutionKey>,
) -> SubstitutionCostMap {
    let default_cost = raw.default_cost();
    let mut closed = SubstitutionCostMap::new();

    for source in tokens {
        if source.is_empty() {
            continue;
        }
        let source_id = token_to_id[source.as_str()];
        for target in tokens {
            if target.is_empty() || source == target {
                continue;
            }
            let target_id = token_to_id[target.as_str()];
            let key = (source.clone(), target.clone());

            let raw_cost = raw.costs.get(&key).copied();
            let closure_cost = *dist.get(source_id, target_id);
            let direct = raw_cost.unwrap_or(default_cost);
            let effective = direct.min(closure_cost);

            if raw_cost.is_some() || effective < default_cost {
                closed.insert(key, effective);
            }
        }
    }

    closed
}

fn project_single_token(
    tokens: &[String],
    token_to_id: &HashMap<&str, NodeId>,
    dist: &Matrix<f64>,
    raw: &CostMap<SingleTokenKey>,
    epsilon_id: NodeId,
    is_insertion: bool,
) -> SingleTokenCostMap {
    let default_cost = raw.default_cost();
    let mut closed = SingleTokenCostMap::new();

    for token in tokens {
        if token.is_empty() {
            continue;
        }
        let id = token_to_id[token.as_str()];
        let raw_cost = raw.costs.get(token).copied();
        let closure_cost = if is_insertion {
            *dist.get(epsilon_id, id)
        } else {
            *dist.get(id, epsilon_id)
        };
        let direct = raw_cost.unwrap_or(default_cost);
        let effective = direct.min(closure_cost);

        if raw_cost.is_some() || effective < default_cost {
            closed.insert(token.clone(), effective);
        }
    }

    closed
}

#[cfg(test)]
mod tests {
    use super::*;

    fn approx(a: f64, b: f64) -> bool {
        (a - b).abs() < 1e-9
    }

    fn make_sub(pairs: &[((&str, &str), f64)], default: f64, symmetric: bool) -> CostMap<SubstitutionKey> {
        let mut map = SubstitutionCostMap::new();
        for ((s, t), c) in pairs {
            map.insert(((*s).to_string(), (*t).to_string()), *c);
        }
        CostMap::<SubstitutionKey>::new(map, default, symmetric)
    }

    fn make_single(pairs: &[(&str, f64)], default: f64) -> CostMap<SingleTokenKey> {
        let mut map = SingleTokenCostMap::new();
        for (k, v) in pairs {
            map.insert((*k).to_string(), *v);
        }
        CostMap::<SingleTokenKey>::new(map, default)
    }

    #[test]
    fn closure_finds_substitution_chain() {
        let sub = make_sub(&[(("a", "b"), 0.1), (("b", "c"), 0.1)], 1.0, false);
        let ins = make_single(&[], 1.0);
        let del = make_single(&[], 1.0);
        let (closed_sub, _, _) = compute_closed_cost_maps(&sub, &ins, &del);
        assert!(approx(closed_sub[&("a".to_string(), "c".to_string())], 0.2));
    }

    #[test]
    fn closure_finds_deletion_chain() {
        let sub = make_sub(&[(("6", "G"), 0.5)], 1.0, false);
        let ins = make_single(&[], 1.0);
        let del = make_single(&[("G", 0.01)], 1.0);
        let (_, _, closed_del) = compute_closed_cost_maps(&sub, &ins, &del);
        assert!(approx(closed_del["6"], 0.51));
    }

    #[test]
    fn closure_finds_insertion_chain() {
        let sub = make_sub(&[(("x", "y"), 0.2)], 1.0, false);
        let ins = make_single(&[("x", 0.1)], 1.0);
        let del = make_single(&[], 1.0);
        let (_, closed_ins, _) = compute_closed_cost_maps(&sub, &ins, &del);
        assert!(approx(closed_ins["y"], 0.3));
    }

    #[test]
    fn closure_finds_repeated_insertion_substitution() {
        // A -> AA -> AAA -> B at cost 0.2 + 0.2 + 0.1 = 0.5
        let sub = make_sub(&[(("AAA", "B"), 0.1)], 1.0, true);
        let ins = make_single(&[("A", 0.2)], 1.0);
        let del = make_single(&[], 1.0);
        let (closed_sub, _, _) = compute_closed_cost_maps(&sub, &ins, &del);
        assert!(approx(closed_sub[&("A".to_string(), "B".to_string())], 0.5));
    }

    #[test]
    fn closure_composes_del_ins_sub() {
        // ADC -> AC -> ABC -> Z at cost 0.1 + 0.1 + 0.1 = 0.3
        let sub = make_sub(&[(("ABC", "Z"), 0.1)], 1.0, true);
        let ins = make_single(&[("B", 0.1)], 1.0);
        let del = make_single(&[("D", 0.1)], 1.0);
        let (closed_sub, _, _) = compute_closed_cost_maps(&sub, &ins, &del);
        assert!(approx(closed_sub[&("ADC".to_string(), "Z".to_string())], 0.3));
    }

    #[test]
    fn closure_preserves_direct_when_chain_more_expensive() {
        let sub = make_sub(&[(("6", "G"), 0.5)], 1.0, false);
        let ins = make_single(&[], 1.0);
        let del = make_single(&[("6", 0.2), ("G", 0.01)], 1.0);
        let (_, _, closed_del) = compute_closed_cost_maps(&sub, &ins, &del);
        assert!(approx(closed_del["6"], 0.2));
    }

    #[test]
    fn closure_idempotent_pure_substitution() {
        // Pure substitution chains converge in one closure round: round 1 adds
        // (a,c) at 0.2; round 2 sees it directly, finds the same path through b.
        let sub = make_sub(&[(("a", "b"), 0.1), (("b", "c"), 0.1)], 1.0, false);
        let ins = make_single(&[], 1.0);
        let del = make_single(&[], 1.0);
        let (s1, i1, d1) = compute_closed_cost_maps(&sub, &ins, &del);
        let sub2 = CostMap::<SubstitutionKey>::new(s1.clone(), 1.0, false);
        let ins2 = CostMap::<SingleTokenKey>::new(i1.clone(), 1.0);
        let del2 = CostMap::<SingleTokenKey>::new(d1.clone(), 1.0);
        let (s2, i2, d2) = compute_closed_cost_maps(&sub2, &ins2, &del2);
        assert_eq!(s1, s2);
        assert_eq!(i1, i2);
        assert_eq!(d1, d2);
    }
}
